[package]
name = "zoneinfo_data"
version = "0.1.0"
authors = ["Ben S <ogham@bsago.me>"]

[lib]
name = "zoneinfo_data"

[dependencies]
locale = "*"

[dependencies.datetime]
git = "https://github.com/rust-datetime/datetime.git"